sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Wang0324
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDVRS4AcAugPk9F5ybd
    access-key-secret: MjxIEq2vK5qbiUu3bAn3lJGODBONKk
    bucket-name: webfile-mt
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
